// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Admin/internal/biz"
	"Admin/internal/conf"
	"Admin/internal/data"
	"Admin/internal/registry"
	"Admin/internal/server"
	"Admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	twitterAccountRepo := data.NewTwitterAccountRepo(dataData, logger)
	twitterAccountUsecase := biz.NewTwitterAccountUsecase(twitterAccountRepo, logger)
	twitterAccountService := service.NewTwitterAccountService(twitterAccountUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, twitterAccountService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, twitterAccountService, logger)
	registrar, err := registry.NewNacosRegistry(confRegistry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
