// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Admin/internal/biz"
	"Admin/internal/conf"
	"Admin/internal/data"
	"Admin/internal/server"
	"Admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
// func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger, bc *conf.Bootstrap) (*kratos.App, func(), error) {
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger, bc *conf.Bootstrap) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	twitterAccountRepo := data.NewTwitterAccountRepo(dataData, logger)
	twitterAccountUsecase := biz.NewTwitterAccountUsecase(twitterAccountRepo, logger)
	twitterAccountService := service.NewTwitterAccountService(twitterAccountUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, twitterAccountService, logger)
	instagramAccountRepo := data.NewInstagramAccountRepo(dataData, logger)
	instagramAccountUsecase := biz.NewInstagramAccountUsecase(instagramAccountRepo, logger)
	instagramAccountService := service.NewInstagramAccountService(instagramAccountUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, twitterAccountService, instagramAccountService, logger)
	app := newApp(bc, logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
