name: fetcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - aiohttp>=3.8.0
    - asyncio>=3.4.3
    - celery>=5.3.0
    - aio-pika>=9.0.0
    - psycopg2-binary>=2.9.0
    - playwright>=1.35.0
    - python-dotenv>=1.0.0
    - pytest>=7.0.0
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.1.0
    - typing-extensions>=4.5.0 