CREATE USER fetcher WITH PASSWORD 'V2KMm4DgfKoCq9iw';
CREATE DATABASE fetcher;

GRANT ALL PRIVILEGES ON DATABASE fetcher TO postgres;
GRANT ALL PRIVILEGES ON DATABASE fetcher TO fetcher;

\c fetcher;

GRANT ALL ON SCHEMA public TO fetcher;
GRANT ALL ON ALL TABLES IN SCHEMA public TO fetcher;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO fetcher;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fetcher;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO fetcher;