# Base configuration shared across all environments
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - graph-weaver_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - volumes/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - graph-weaver_network
    restart: unless-stopped

networks:
  graph-weaver_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: 