name: Build and Push Admin-UI Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'admin-ui/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate .env from secrets
        run: |
          echo "${{ secrets.ADMIN_UI_ENV }}" > admin-ui/.env
      - uses: docker/build-push-action@v5
        with:
          context: ./admin-ui
          file: ./admin-ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastkol-admin-ui:latest
          no-cache: true